server:
  port: 8093
spring:
  #数据库连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver # com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems-dev?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: passw@rd
    druid:
      initial-size: 3
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-log-stats-millis: 300000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      filters: stat, slf4j
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 10000
        slf4j:
          result-set-log-enabled: false
          statement-executable-sql-log-enable: false
      stat-view-servlet:
        enabled: true












